=== varun070298/webmail-0.7.10/src/net/wastl/webmail/data/xml/userdata.dtd
<?xml encoding="UTF-8"?>

<!-- This represents static userdata that will be saved to disk or to a database -->

<!ELEMENT USERDATA (LOGIN,PASSWORD,PASSDATA,USER_DOMAIN,FULL_NAME,EMAIL,SIGNATURE,LOCALE,THEME,MAILHOST*,BOOLVAR*,INTVAR*,SENT_FOLDER?,COMMENT?)>
<!ELEMENT LOGIN (#PCDATA)>
<!ELEMENT PASSWORD (#PCDATA)>
<!ELEMENT PASSDATA (#PCDATA)>
<!ELEMENT USER_DOMAIN (#PCDATA)>
<!ELEMENT FULL_NAME (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT SIGNATURE (#PCDATA)>
<!ATTLIST SIGNATURE
	xml:space 	(default|preserve) 	'preserve'>
<!ELEMENT LOCALE (#PCDATA)>
<!ELEMENT THEME (#PCDATA)>
<!ELEMENT MAILHOST (MH_LOGIN,MH_PASSWORD,MH_URI)>
<!ELEMENT BOOLVAR EMPTY>
<!ELEMENT INTVAR EMPTY>
<!ELEMENT SENT_FOLDER (#PCDATA)>

<!ELEMENT MH_URI (#PCDATA)>
<!ELEMENT MH_LOGIN (#PCDATA)>
<!ELEMENT MH_PASSWORD (#PCDATA)>

<!ATTLIST MAILHOST    name  CDATA       #REQUIRED
                      id    CDATA       #REQUIRED>

<!-- This is not yet used but may perhaps allow to provide some sort of finger-like
     information -->
<!ELEMENT COMMENT (#PCDATA)>

<!-- Currently (0.7) the following INTVARs are used in WebMail:
"show images"		- Show attached images inline
"show fancy"		- Show fancy stuff (Replace smilies with icons, ...)
"filter javascript"	- Remove JavaScript from HTML messages (security)
"set message flags"	- Allow WebMail to write on folders (for message flagging, deletion, etc)
"save sent messages"	- Save sent messages to a folder (SENT_FOLDER)
-->
<!ATTLIST BOOLVAR     name  CDATA       #REQUIRED
                      value (yes|no)    #IMPLIED>

<!-- Currently (0.7) the following INTVARs are used in WebMail:
"first login"		- The first login of a user in seconds since 1.1.1970 (for a formated string see statedata.dtd)
"last login"		- The last login of the user in seconds since 1.1.1970
"login count"		- The number of logins this user already had
"max show messages" 	- The number of messages to show on a page in the message list
"icon size" 		- The size of the navbar icons (for default layout).
-->
<!ATTLIST INTVAR      name  CDATA       #REQUIRED
                      value CDATA       #IMPLIED>

=== varun070298/webmail-0.7.10/src/net/wastl/webmail/data/xml/userdata.xml
<?xml version="1.0"?>

<!DOCTYPE USERDATA SYSTEM "userdata.dtd">

<USERDATA>
  <LOGIN></LOGIN>
  <PASSWORD></PASSWORD>
  <PASSDATA></PASSDATA>
  <USER_DOMAIN></USER_DOMAIN>
  <FULL_NAME></FULL_NAME>
  <EMAIL></EMAIL>
  <SIGNATURE></SIGNATURE>
  <LOCALE></LOCALE>
  <THEME></THEME>
  <BOOLVAR name="show fancy" value="yes"/>
  <BOOLVAR name="show images" value="yes"/>
  <BOOLVAR name="save sent messages" value="no"/>
  <BOOLVAR name="set message flags" value="yes"/>
  <INTVAR name="first login"/>
  <INTVAR name="last login"/>
  <INTVAR name="login count"/>
  <INTVAR name="max show messages"/>
</USERDATA>
