=== varun070298/webmail-0.7.10/src/doc/readme/README.dtd
<!-- DTD for WebMail README -->

<!-- CVS ID: $Id: README.dtd,v 1.1.1.1 2002/10/02 18:41:43 wastl Exp $ -->

<!--
 * Copyright (C) 2000 Sebastian Schaffert
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<!ELEMENT README (TITLE,AUTHOR,SECTION+)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT SECTION (SUBSECTION|P|CONTENTS)*>
<!ELEMENT CONTENTS (#PCDATA)>
<!ELEMENT SUBSECTION (SUBSUBSECTION|P)*>
<!ELEMENT SUBSUBSECTION (P)*>
<!ELEMENT P (#PCDATA|LIST|NLIST|NOTE|TABLE|STRONG|CODE|EM|A|BR)*>
<!ELEMENT LIST (ITEM)*>
<!ELEMENT NLIST (ITEM)*>
<!ELEMENT ITEM (#PCDATA|TABLE|P|STRONG|CODE|EM|A|BR)*>
<!ELEMENT NOTE (#PCDATA|STRONG|CODE|EM|A|BR)*>
<!ELEMENT STRONG (#PCDATA|A|EM)*>
<!ELEMENT EM (#PCDATA|A)*>
<!ELEMENT CODE (#PCDATA|STRONG|EM|A|BR)*>
<!ELEMENT BR (#PCDATA)>
<!ELEMENT A (#PCDATA)>
<!ELEMENT TABLE (TR)*>
<!ELEMENT TR (TD)*>
<!ELEMENT TD (#PCDATA|CODE|EM|STRONG|A)*>

<!-- Sections, Subsections and Subsubsections require a name (the title of the section)
     and a unique ID within the document for referencing -->
<!ATTLIST SECTION       name CDATA #REQUIRED
                        id   CDATA #REQUIRED>
<!ATTLIST SUBSECTION    name CDATA #REQUIRED
                        id   CDATA #REQUIRED>
<!ATTLIST SUBSUBSECTION name CDATA #REQUIRED
                        id   CDATA #REQUIRED>

<!-- Links are very simple here, they just require a reference -->
<!ATTLIST A             href CDATA #REQUIRED>

=== varun070298/webmail-0.7.10/bin/doc/readme/README.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!-- CVS ID: $Id: README.xml,v 1.1.1.1 2002/10/02 18:41:44 wastl Exp $ -->

<!--
 * Copyright (C) 2000 Sebastian Schaffert
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<!DOCTYPE README SYSTEM "README.dtd">

<README>
  <TITLE>WebMail v0.7.2</TITLE>
  <AUTHOR>Sebastian Schaffert, schaffer@informatik.uni-muenchen.de</AUTHOR>
  <SECTION name="Contents" id="contents"><CONTENTS/></SECTION>
  <SECTION name="What is WebMail" id="about">
    <P>
      WebMail is a server application that allows ISPs to provide a WWW interface 
      for each user to his mailbox(es) (similar to the programs YahooMail or HotMail 
      use). WebMail should scale well enough to support large userbases and 
      should be easy enough to be used in a home LAN.
    </P>
    
    <SUBSECTION name="Features" id="about:features">
      <P>
	Features include:
	<LIST>
	  <ITEM>Gives a user full access to his/her IMAP mailbox through a simple-to-use WWW interface</ITEM>
	  <ITEM>Supports multiple folders on multiple hosts, depending on mail protocol used 
	    (IMAP supports different folders on the same host, POP doesn't)</ITEM>
	  <ITEM>Sophisticated folder management system</ITEM>
	  <ITEM>100% HTML 3.2/4.0 output, no Javascript, no Java on the Client side</ITEM>
	  <ITEM>supports multiple languages, configurable for each user</ITEM>
	  <ITEM>flexible template system to personalize look and feel and write new language files using XML and 
	    XSL</ITEM>
	  <ITEM>runs as Java Servlet in Apache or as a standalone HTTP-server completely written in Java</ITEM>
	  <ITEM>Improved session management keeps mail connections alive</ITEM>
	  <ITEM>Improved speed compared to CGI scripts (about factor 5-10, depending on usage)</ITEM>
	  <ITEM>Usage of JavaMail-API ensures compatibility to many mailstandards 
	    ("officially" supported and tested: IMAPv4)</ITEM>
	  <ITEM>Open Source distribution allows easy customization</ITEM>
	  <ITEM>webbased administration interface</ITEM>
	  <ITEM>support for multiple virtual user domains</ITEM>
	  <ITEM>Easily add new features through the WebMail modular plugin concept 
	    (support for dependencies, hooking into URLs, etc)</ITEM>
	</LIST>
      </P>
    </SUBSECTION>

    <SUBSECTION name="Whom WebMail is aimed at" id="about:audience">
      <P>
	Who should use WebMail:<BR/>
	WebMail's primary goal is to provide ISPs, companies and universities with a 
	simple and zero-cost solution to give WWW mailaccess to their users.<BR/>
	Users can read and write their email while they are sitting in an Internet-Cafe,
	at expositions, etc without having to carry their PC around.<BR/>
	It is not intended as a replacement for the different personal email clients, 
	but as a supplement for an existing mail solution.<BR/>
	The secondary goal is to unify a user's different email accounts under one 
	interface which is easily accomplished using WebMails folder capability.
      </P>
    </SUBSECTION>
  </SECTION>

  <SECTION name="Installation" id="install">
    <SUBSECTION name="Introduction" id="install:introduction">
      <P>
        There are two different ways to install WebMail, the <EM>standalone installation</EM> and the
        <EM>Java Servlet installation</EM>. Which one you should choose depends on what you plan to do
	with WebMail:
        <LIST>
          <ITEM>
	    a <STRONG>standalone server</STRONG> is much easier to install and will allow you to run
	    WebMail almost immediately without much configuration. This can be used if you want to
            evaluate WebMail's capabilities or develop new features/bugfixes. It also makes sense to
            use this for small to medium installations if you don't want to set up a Java Servlet
            capable webserver
          </ITEM>
          <ITEM>
            a <STRONG>Java Servlet installation</STRONG> is recommended for production use since it 
	    allows greater performance and scalability. You will need to set up a webserver that is
            capable of serving Java Servlets, e.g. Apache. I can't give too detailed instructions here
            since this depends in large parts on your webserver, but I include a sample Apache 
            configuration (the parts relevant to WebMail) in the distribution.<BR/>
	    The Debian (unstable) and RedHat (6.2) packages will install WebMail as a servlet for these
	    two systems. This will ease the servlet installation a lot since you need not set up JServ and
	    WebMail manually, so you should consider using this approach if you have one of those systems.
          </ITEM>
        </LIST>
      </P>
<!--      <P>
	There are also several ways to store data:
	<LIST>
	  <ITEM>
	    You could use the simple file-based storage which stores configuration data in XML documents 
	    and is very easy to set up, but perhaps not very fast.
	  </ITEM>
	  <ITEM>
	    The performance method however is to store the configuration in a SQL database. Currently
	    only MySQL is supported, but it is easy to implement storage on Oracle or PostgreSQL.
	    Using a SQL database for storage has several advantages which I will describe below.
	  </ITEM>
	</LIST>
      </P>-->
    </SUBSECTION>

    <SUBSECTION name="Standalone Server" id="install:standalone">
      <NOTE>On RedHat and Debian Linux systems you will probably first want to have a look at the
	RedHat and Debian sections in the Servlet installation instructions</NOTE>

      <SUBSUBSECTION name="Requirements" id="install:standalone:requirements">
        <P>
	  To run WebMail properly on your server, you need to have the following software 
	  installed:
          <LIST>
	    <ITEM>Java 1.1.6 or better - see<A href="#java">the Java Section</A> on Java issues</ITEM>
            <ITEM>
              About 20 megs of RAM (minimum) plus additional 80 megs on high load servers
              (these are just recommendations, WebMail will run on any Java-capable server;
              if you have less than 32 MB RAM, you should try to adjust the settings in
              the startup script called webmail.sh/webmail.bat)
            </ITEM>
            <ITEM>
	      Using a JIT ("just in time compiler") is greatly recommended! The Solaris and Windows 
	      JDKs from Sun use a JIT by default (sunwjit). On Linux, the Sun/Blackdown JDK uses a JIT,
	      however it is not very fast, so you could profit from using a JIT like tya. The IBM Linux 
              JDK 1.1.8 comes with a very fast JIT (actually the fastest Java platform available).
            </ITEM>
          </LIST>
        </P>
        <P>
          WebMail has been successfully tested on:
          <LIST>
            <ITEM>Solaris x86 and SPARC, JDK 1.1.6 and JDK 1.2</ITEM>
            <ITEM>Linux x86 (tested: Debian and SuSE), IBM JDK 1.1.8 and Sun/Inprise JDK 1.2.2 (RC3)</ITEM>
            <ITEM>FreeBSD 3.4 x86, JDK 1.1.8</ITEM>
            <ITEM>Windows NT/2000 (did not do the tests myself)</ITEM>
          </LIST>
        </P>
        <P>
	  WebMail will make profit of multiprocessor machines (e.g. Sun Enterprise 450) as
	  it is multithreaded in large parts.<BR/>
        </P>
      </SUBSUBSECTION>

      <SUBSUBSECTION name="Binary Installation" id="install:standalone:binary">
        <P>
          <NLIST>
	    <ITEM>Change to the prefix where you want to install WebMail (e.g. /usr/local)</ITEM>
            <ITEM>Unpack the tar.gz or zip archive: <CODE>tar xzvf webmail-0.7.0.tar.gz</CODE></ITEM>
            <ITEM>Change to webmail/bin</ITEM>
	    <ITEM>Edit the file webmail.sh if necessary</ITEM>
            <ITEM>Start WebMail using the provided script 
	      <CODE>./webmail.sh >> stdout.log 2>&amp;1 &amp;</CODE></ITEM>
            <ITEM>See <A href="#config">Configuration</A> for further steps to take.</ITEM>
          </NLIST>
        </P>
      </SUBSUBSECTION>

      <SUBSUBSECTION name="Source Installation" id="install:standalone:source">
        <P>
          <NOTE>Source installation will definately only work on Unix systems!</NOTE>
          <NOTE>Source installation is only really useful for developers since you don't need to
	    (and cannot) adapt the program to your specific system settings in Java and I already
	    compile with optimization turned on.</NOTE>
	</P>
        <P>
	  Additional requirements:
          <LIST>
	    <ITEM>GNU make (Only GNU make will work)</ITEM>
            <ITEM>zip/unzip</ITEM>
          </LIST>
        </P>
        <P>
          To install the source distribution of WebMail you will have to take the following steps:
          <NLIST>
            <ITEM>Change to the src/ subdirectory</ITEM>
            <ITEM>Set the CLASSPATH environment variable to your classes.zip (JDK 1.1) or
	      rt.jar (JDK 1.2) archives (on Solaris: /usr/java1.1/lib/classes.zip for
	      JDK 1.1 and /usr/java1.2/jre/lib/rt.jar for JDK 1.2)
            </ITEM>
            <ITEM>Have a look at the makefile and edit it if necessary</ITEM>
            <ITEM>
              Call "make" to compile the classfiles and create the archives
	      (containing classfiles, language dependent HTML templates and images).<BR/>            
	      You will find the compiled archives in the lib/ directory when the 
              compilation was successful. 
            </ITEM>
